##---------------------------------------------------------------------------##
## Project properties
##---------------------------------------------------------------------------##
---
dev:
  base_url: http://localhost:8888/spring-rest/rest
