package com.springclass.stubs.dao;

import com.springclass.dao.LoanDAO;
import com.springclass.domain.Loan;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * <p>
 * CREATE MEMORY TABLE LOAN(
 *   LOAN_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1001,INCREMENT BY 10) NOT NULL PRIMARY KEY,
 *   MEMBER_ID VARCHAR(10),
 *   DVDCODE VARCHAR(10),
 *   FROM_LOCATION VARCHAR(10),
 *   LOAN_DATE DATE,EXPECTED_RETURN_LOCATION VARCHAR(10),
 *   EXPECTED_RETURN_DATE DATE,
 *   CONSTRAINT FK_LOAN_FOR_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID))
 * </p>
 * This component and its source code representation are copyright protected
 * and proprietary to The Trivera Group, Inc., Worldwide D/B/A Trivera Technologies
 *
 * This component and source code may be used for instructional and
 * evaluation purposes only. No part of this component or its source code
 * may be sold, transferred, or publicly posted, nor may it be used in a
 * commercial or production environment, without the express written consent
 * of the Trivera Group, Inc.
 *
 * Copyright (c) 2014 The Trivera Group, LLC.
 * http://www.triveratech.com   http://www.triveragroup.com
 * </p>
 * @author The Trivera Group Tech Team.
 */
@Component
public class LoanDAOImpl implements LoanDAO {

    private final Logger logger = LoggerFactory.getLogger(this.getClass());

    public int addLoan(Loan loan){
        logger.info("Loan Added: {}", loan);

        return 9494;
    }
}
